# Generated by Django 3.2 on 2021-04-08 14:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_sell_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='status',
            field=models.CharField(choices=[('cart', 'cart'), ('sold', 'sold')], default='cart', max_length=4, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sell',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
    ]
